# 21.3mm, 6.5mm
target_type: 'aprilgrid'    #gridtype
tagCols: 6                  #number of apriltags
tagRows: 6                  #number of apriltags
tagSize: 0.0213             #size of apriltag, edge to edge [m]
tagSpacing: 0.3             #ratio of space between tags to tagSize. Example: tagSize=2m, spacing=0.5m --> tagSpacing=0.25[-]
codeOffset: 0               #code offset for the first tag in the aprilboard
